### PR TITLE
mod default value of RPCTxFeeCap

### LINKED ISSUE #144: Need to change the default cap on transaction fee (1 ether) that can be sent via the RPC APIs
Encountered the error `“Failed to submit mined result         shard=0 block=7,350,229 error="tx fee (164.48 ether) exceeds the configured cap (1.00 ether)”` while submitting the EthStorage mining transaction

Since we’re using QKC instead of ETH to measure the gas fee, we may need to increase the default cap for --rpc.txfeecap from 1 to 1000, as suggested by @qizhou.

### PR DESCRIPTION
**Pull request by blockchaindevsh**
Fixes https://github.com/ethstorage/optimism/issues/144 .

### CODE REVIEW

**Review by qzhodl — APPROVED** [review]

File: eth/ethconfig/config.go [hunk 1]
```diff
@@ -66,7 +66,7 @@ var Defaults = Config{
 	RPCGasCap:          50000000,
 	RPCEVMTimeout:      5 * time.Second,
 	GPO:                FullNodeGPO,
-	RPCTxFeeCap:        1, // 1 ether
+	RPCTxFeeCap:        1000, // 1 ether
```
Comment (qizhou) [inline eth/ethconfig/config.go]: The comment should be updated acccordingly.

Comment (blockchaindevsh) [reply eth/ethconfig/config.go]: Done in 9174f0f42333c4b52a05e84af1821bf8d32b919e.

**Review by syntrust — APPROVED** [review]

**Review by qizhou — APPROVED** [review]
